{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.952.0 (24.04)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dim_customers\",\"dim_date\",\"dim_products\",\"dim_targets_orders\",\"fact_order_lines\",\"fact_orders_aggregate\",\"_0KeyMeasure\",\"_Humayun\",\"_Tanvir\",\"_Farhana\",\"_IfatFeroji\",\"_Diponkor\",\"_Yousuf\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "2769d8e0-4b55-4771-b7d9-1509575b29e2",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "customer_id",
        "fromTable": "dim_targets_orders",
        "toColumn": "customer_id",
        "toTable": "dim_customers"
      },
      {
        "name": "f3a028c4-ba5c-4d11-ba16-aaec65dbff34",
        "fromColumn": "customer_id",
        "fromTable": "fact_order_lines",
        "toColumn": "customer_id",
        "toTable": "dim_customers"
      },
      {
        "name": "62ff033e-b9e9-41ee-82b7-9b44074ab874",
        "fromColumn": "product_id",
        "fromTable": "fact_order_lines",
        "toColumn": "product_id",
        "toTable": "dim_products"
      },
      {
        "name": "6c8160f4-652a-4f22-898f-7dfea92f9b39",
        "fromColumn": "customer_id",
        "fromTable": "fact_orders_aggregate",
        "toColumn": "customer_id",
        "toTable": "dim_customers"
      },
      {
        "name": "169b8437-2360-4a8d-bfba-002c68bfcf0d",
        "fromColumn": "order_id",
        "fromTable": "fact_order_lines",
        "isActive": false,
        "toColumn": "order_id",
        "toTable": "fact_orders_aggregate"
      },
      {
        "name": "555c90a4-637f-437f-9f8c-89ccf3ec9911",
        "fromColumn": "order_placement_date",
        "fromTable": "fact_orders_aggregate",
        "toColumn": "date",
        "toTable": "dim_date"
      },
      {
        "name": "e91e9fef-2afe-4178-93b5-c014aa2072aa",
        "fromColumn": "agreed_delivery_date",
        "fromTable": "fact_order_lines",
        "isActive": false,
        "toColumn": "date",
        "toTable": "dim_date"
      },
      {
        "name": "01c55223-a645-44b9-9c3e-12801179b68e",
        "fromColumn": "customer_id",
        "fromTable": "fact_orders_aggregate",
        "isActive": false,
        "toColumn": "customer_id",
        "toTable": "dim_targets_orders"
      },
      {
        "name": "2d06cb4e-a2d3-4978-b77a-a66de2fc9fb0",
        "fromColumn": "order_placement_date",
        "fromTable": "fact_order_lines",
        "toColumn": "date",
        "toTable": "dim_date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "dim_customers",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a3c854a-3cd6-41d8-90d9-c146b52e20e1",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bdbedfa-2fe3-43e4-b4b0-71a9f37abed3",
            "sourceColumn": "customer_name",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "306e7d54-cab0-4431-9c24-4d57ed2d4381",
            "sourceColumn": "city",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "99b28069-e662-4a68-af5a-d51195fe14e1",
        "partitions": [
          {
            "name": "dim_customers",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1RhJSmnLrXFgi6sUUmbYWVe1iysUI6mJ9\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_id\", Int64.Type}, {\"customer_name\", type text}, {\"city\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "68558bec-a724-47b6-827f-731ee1302030",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "mmm_yy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "8e987f4c-840f-4114-8cd0-666e3e11b8ad",
            "sourceColumn": "mmm_yy",
            "summarizeBy": "none"
          },
          {
            "name": "week_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebbb4748-55d5-49c7-8144-27ba5cb19c6b",
            "sourceColumn": "week_no",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3424feac-9249-4881-abfe-761436386749",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "65b525a3-a9f3-4a99-ae68-caff52a93f14",
            "sortByColumn": "month_no",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "month_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(dim_date[date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "956ef7d1-04d8-416a-b120-352bf8da1292",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "3b52e0f1-04ef-43f9-822f-59cbf418d6f1",
        "partitions": [
          {
            "name": "dim_date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1Fx312rOTS_P2rNDsc4DRDtipveRYgksc\"),[Delimiter=\",\", Columns=3, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"date\", type date}, {\"mmm_yy\", type date}, {\"week_no\", type text}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([date]), Int64.Type),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Year\", \"Month Name\", each Date.MonthName([date]), type text)",
                "in",
                "    #\"Inserted Month Name\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_products",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "product_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "644d147e-1608-4c0e-8dc1-7e1d687ed804",
            "sourceColumn": "product_name",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9c166d96-1805-4872-b4bb-872e25b09b2c",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0976f3ac-aa7c-4405-bdac-3eb5071c9afd",
            "sourceColumn": "category",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2fec89d3-d01c-4d03-9861-718bcfbc0082",
        "partitions": [
          {
            "name": "dim_products",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1snFFQkJgKU8J-z2lhy6FtsWUCnIeGS9u\"),[Delimiter=\",\", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"product_name\", type text}, {\"product_id\", Int64.Type}, {\"category\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dim_targets_orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f2648c8a-58f7-4d91-ab65-1e0e36abe731",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "ontime_target%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8bd9481c-9ce6-4386-a8ca-0e64e75ad24d",
            "sourceColumn": "ontime_target%",
            "summarizeBy": "sum"
          },
          {
            "name": "infull_target%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "82147e1a-dd5f-4be8-b057-3758964ffe3c",
            "sourceColumn": "infull_target%",
            "summarizeBy": "sum"
          },
          {
            "name": "otif_target%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "52d6ea8d-a997-456d-99fb-7bc7f1b18753",
            "sourceColumn": "otif_target%",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "8b932551-9b2f-475d-aaa4-daa45364e8e1",
        "partitions": [
          {
            "name": "dim_targets_orders",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1rwrx9MAIb9QlLUgL25ubY6d8a3UYKZYa\"),[Delimiter=\",\", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"customer_id\", Int64.Type}, {\"ontime_target%\", Int64.Type}, {\"infull_target%\", Int64.Type}, {\"otif_target%\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_order_lines",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f52e8414-ab39-4da5-bacf-c74ba90bc359",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_placement_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "d0051054-792f-4076-bcc7-ad22d0bca941",
            "sourceColumn": "order_placement_date",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8f84de9c-7783-4798-aca9-7dd7205e677d",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "product_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a84d6180-55ff-474d-9c55-304d3dac80c2",
            "sourceColumn": "product_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "efc8cfc3-9e0c-406d-a363-0c2d498402c5",
            "sourceColumn": "order_qty",
            "summarizeBy": "sum"
          },
          {
            "name": "agreed_delivery_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "517bebfa-cf5f-46ac-8879-286d6f448d6a",
            "sourceColumn": "agreed_delivery_date",
            "summarizeBy": "none"
          },
          {
            "name": "actual_delivery_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "3dda2e5b-0dce-4c88-9b4d-cd984af1586a",
            "sourceColumn": "actual_delivery_date",
            "summarizeBy": "none"
          },
          {
            "name": "delivery_qty",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0039e579-c4b1-41ef-aec2-45e077bfe614",
            "sourceColumn": "delivery_qty",
            "summarizeBy": "sum"
          },
          {
            "name": "In Full",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d796f5ea-7c06-42aa-809e-161e61a6fd57",
            "sourceColumn": "In Full",
            "summarizeBy": "sum"
          },
          {
            "name": "On Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f42e549-4f66-4dd9-a4f5-2539df35217f",
            "sourceColumn": "On Time",
            "summarizeBy": "sum"
          },
          {
            "name": "On Time In Full",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aea57025-7228-4f43-a50f-82b9b50b31bc",
            "sourceColumn": "On Time In Full",
            "summarizeBy": "sum"
          },
          {
            "name": "Delayed_Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    fact_order_lines[actual_delivery_date] - fact_order_lines[agreed_delivery_date]"
            ],
            "formatString": "0",
            "lineageTag": "c050b9cb-464e-4f11-9fd0-c02864d74aae",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "0dd25096-dff5-46fb-a383-46296d5c36b0",
        "partitions": [
          {
            "name": "fact_order_lines",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=1xCzGjpsnLN-7WHBGSx9-a7QB5KiJmrGG\"),[Delimiter=\",\", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"order_id\", type text}, {\"order_placement_date\", type date}, {\"customer_id\", Int64.Type}, {\"product_id\", Int64.Type}, {\"order_qty\", Int64.Type}, {\"agreed_delivery_date\", type date}, {\"actual_delivery_date\", type date}, {\"delivery_qty\", Int64.Type}, {\"In Full\", Int64.Type}, {\"On Time\", Int64.Type}, {\"On Time In Full\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "fact_orders_aggregate",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "order_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "280a9276-328c-4d3e-92ff-b48c4ed0e868",
            "sourceColumn": "order_id",
            "summarizeBy": "none"
          },
          {
            "name": "customer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9509bbf9-d1db-4c1b-b61b-652fd31d4a9f",
            "sourceColumn": "customer_id",
            "summarizeBy": "none"
          },
          {
            "name": "order_placement_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "b906cb5b-6682-4b6f-8b04-3868687dc991",
            "sourceColumn": "order_placement_date",
            "summarizeBy": "none"
          },
          {
            "name": "on_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "91e1013e-b7d0-43ba-bd36-1121c4b74316",
            "sourceColumn": "on_time",
            "summarizeBy": "sum"
          },
          {
            "name": "in_full",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "03cb08fa-f1c1-490c-8d2c-458a1a427e02",
            "sourceColumn": "in_full",
            "summarizeBy": "sum"
          },
          {
            "name": "otif",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e094a559-bda5-4819-80ee-46cb3d6db823",
            "sourceColumn": "otif",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "b5ef97ba-4cbe-45c5-8330-b04c10d5df4e",
        "partitions": [
          {
            "name": "fact_orders_aggregate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://drive.google.com/uc?export=download&id=15KBY4MZ4fRXofZkZCe89psOHcoTECq6q\"),[Delimiter=\",\", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"order_id\", type text}, {\"customer_id\", Int64.Type}, {\"order_placement_date\", type date}, {\"on_time\", Int64.Type}, {\"in_full\", Int64.Type}, {\"otif\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_0KeyMeasure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "a24c5b9f-dbf3-4653-83d7-ebe1a71bffbb",
        "measures": [
          {
            "name": "Total Order Line",
            "displayFolder": "fact_order_lines",
            "expression": [
              "",
              "COUNT(fact_order_lines[order_id])"
            ],
            "formatString": "#,0",
            "lineageTag": "34846f4d-8267-4d33-b821-ac6a58b23b83"
          },
          {
            "name": "Total_Orders_Counts",
            "displayFolder": "fact_orders_aggregate",
            "expression": [
              "",
              "    DISTINCTCOUNT(fact_orders_aggregate[order_id])"
            ],
            "formatString": "0",
            "lineageTag": "fc015d30-bcb9-4993-94d9-28719ac5c071"
          },
          {
            "name": "LIFR %",
            "displayFolder": "fact_order_lines",
            "expression": [
              "",
              "    DIVIDE([OrderLine_InFull], [Total Order Line])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c6f07a99-b2ef-4b70-9d8e-2ee25f699a04"
          },
          {
            "name": "VOFR %",
            "displayFolder": "fact_order_lines",
            "expression": [
              "",
              "    DIVIDE([Total_Order_LineQty_Deliver],[Total_Qty_Order])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4de0bb30-458e-4551-b846-375be7e4cb4e"
          },
          {
            "name": "OT_Target%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "dim_targents_orders",
            "expression": [
              "",
              "    AVERAGE(dim_targets_orders[ontime_target%])"
            ],
            "lineageTag": "d173876b-088d-4be8-818c-51eea9a3524f"
          },
          {
            "name": "IF_Target%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "dim_targents_orders",
            "expression": [
              "",
              "    AVERAGE(dim_targets_orders[infull_target%])",
              "",
              "",
              "    "
            ],
            "lineageTag": "9eb94635-2218-4c98-909b-095b512b98d6"
          },
          {
            "name": "OTIF_Target%",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "dim_targents_orders",
            "expression": [
              "",
              "    AVERAGE(dim_targets_orders[otif_target%])"
            ],
            "lineageTag": "23356070-80f2-4f2b-b6af-cf3ada18f03c"
          },
          {
            "name": "OnTimeDelivery %",
            "displayFolder": "fact_orders_aggregate",
            "expression": [
              "",
              "    VAR _OnTiD = CALCULATE(",
              "        COUNT(fact_orders_aggregate[customer_id]),",
              "        FILTER( fact_orders_aggregate, fact_orders_aggregate[on_time] = 1 )",
              "        )",
              "    RETURN",
              "        DIVIDE(_OnTiD, [Total_Orders_Counts])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3fd63d09-6bb9-400d-a290-1d82bfbc5084"
          },
          {
            "name": "InFullDelivery %",
            "displayFolder": "fact_orders_aggregate",
            "expression": [
              "",
              "      VAR _InFuD = CALCULATE(",
              "        COUNT(fact_orders_aggregate[customer_id]),",
              "        FILTER( fact_orders_aggregate, fact_orders_aggregate[in_full] = 1 )",
              "        )",
              "    RETURN",
              "        DIVIDE(_InFuD, [Total_Orders_Counts])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "7e538bee-e788-4431-ab30-f73a118c12cb"
          },
          {
            "name": "OnTimeInFullDelivery %",
            "displayFolder": "fact_orders_aggregate",
            "expression": [
              "",
              "      VAR _OnTiInFulD = CALCULATE(",
              "        COUNT(fact_orders_aggregate[customer_id]),",
              "        FILTER( fact_orders_aggregate, fact_orders_aggregate[otif] = 1 )",
              "        )",
              "    RETURN",
              "        DIVIDE(_OnTiInFulD, [Total_Orders_Counts])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "8155de55-9ed5-4c14-bae2-ad2eac57b062"
          }
        ],
        "partitions": [
          {
            "name": "_0KeyMeasure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Humayun",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "14da1da4-aa82-4002-9d74-a3084489b3d5",
        "measures": [
          {
            "name": "Customer_Order",
            "expression": [
              "",
              "",
              "    DIVIDE(",
              "        COUNTROWS(FILTER(fact_order_lines, fact_order_lines[customer_id])),",
              "        CALCULATE(COUNTROWS(fact_order_lines), ALLSELECTED(fact_order_lines)",
              "))",
              "",
              "/*",
              "  VAR _custo = COUNTROWS(fact_order_lines)",
              "",
              "   RETURN",
              "    CALCULATE(_custo, ALLEXCEPT(fact_order_lines, fact_order_lines[customer_id]))",
              "    */"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3bb4cf07-0aa7-453e-ad09-54e0eef08dc6"
          },
          {
            "name": "OrderLine_InFull",
            "expression": [
              "",
              "    CALCULATE([Total Order Line], fact_order_lines[In Full] = 1)"
            ],
            "formatString": "0",
            "lineageTag": "e4610981-cab4-4208-9943-4c32ec3e8941"
          },
          {
            "name": "Total_Order_LineQty",
            "expression": [
              "",
              "    SUM(fact_order_lines[order_qty])"
            ],
            "formatString": "#,0",
            "lineageTag": "2048f22e-3f3a-49e4-9544-bf83fe3a4dfb"
          },
          {
            "name": "Total_Order_LineQty_Deliver",
            "expression": [
              "",
              "    SUM(fact_order_lines[delivery_qty])"
            ],
            "formatString": "#,0",
            "lineageTag": "2aaf60e2-1699-43a6-bf42-6ca482903d6b"
          },
          {
            "name": "Total_Qty_Order",
            "expression": [
              "",
              "    SUM(fact_order_lines[order_qty])"
            ],
            "formatString": "0",
            "lineageTag": "0ff107b2-b2bc-4834-b393-f232a57e38ce"
          },
          {
            "name": "InFull_Orders",
            "expression": [
              "",
              "    SUM(fact_orders_aggregate[in_full])"
            ],
            "formatString": "0",
            "lineageTag": "392dc509-250a-44ed-a1cc-c61ed1cdb549"
          },
          {
            "name": "OnTime_Orders",
            "expression": [
              "",
              "    SUM(fact_orders_aggregate[on_time])"
            ],
            "formatString": "0",
            "lineageTag": "83f71703-df9d-437d-a8d7-277ddb6ed509"
          },
          {
            "name": "OnTimeInFull_Orders",
            "expression": [
              "",
              "    SUM(fact_orders_aggregate[otif])"
            ],
            "formatString": "#,0",
            "lineageTag": "615c8893-69e3-42c6-a337-fb541ae1907d"
          }
        ],
        "partitions": [
          {
            "name": "_Humayun",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Tanvir",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff2c6510-08d3-4a7d-8c03-1a488d8d87c4",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bdb5bbde-6d38-4a95-85ca-babef7782c5a",
        "partitions": [
          {
            "name": "_Tanvir",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Farhana",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0b63e60-b464-4731-b102-9302545a6544",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "80d01fcc-fd58-4a81-96d8-79fb37c68706",
        "measures": [
          {
            "name": "On Time Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "DIVIDE(AVERAGE(dim_targets_orders[ontime_target%]), 100)",
              ""
            ],
            "lineageTag": "51cbf14d-4582-4613-98d0-c5d07d0732cc"
          },
          {
            "name": "In Full Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "DIVIDE(AVERAGE(dim_targets_orders[infull_target%]),100)",
            "lineageTag": "bbf1751d-7269-4dbe-be05-9fb1ac9b3c99"
          },
          {
            "name": "On Time In Full Target",
            "expression": "DIVIDE(AVERAGE(dim_targets_orders[otif_target%]),100)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "222abee5-91b4-45db-896c-ee1168456a55"
          },
          {
            "name": "OT %",
            "expression": "DIVIDE(SUM(fact_orders_aggregate[on_time]), COUNT(fact_orders_aggregate[order_id]), 0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "01cd6b73-a0dd-4ae7-8ec8-224454889c4a"
          },
          {
            "name": "OT% Variance",
            "expression": "(([OT %] - [On Time Target]) / [On Time Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f536433a-591b-4902-bd30-7a2637254c30"
          },
          {
            "name": "IF %",
            "expression": "DIVIDE(SUM(fact_orders_aggregate[in_full]), COUNT(fact_orders_aggregate[order_id]), 0) ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0d0f5524-a651-48b8-b748-aac030dce381"
          },
          {
            "name": "OTIF %",
            "expression": "DIVIDE(SUM(fact_orders_aggregate[otif]), COUNT(fact_orders_aggregate[order_id]), 0) ",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "12d03a74-1ec6-46c6-96d7-91ec26a7c900"
          },
          {
            "name": "IF% Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(([IF %] - [In Full Target]) / [In Full Target]) * 100",
            "lineageTag": "d8b4057f-2e49-4df5-9c30-c076850d26e6"
          },
          {
            "name": "OTIF% Variance",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(([OTIF %] - [On Time In Full Target]) / [On Time In Full Target]) * 100",
            "lineageTag": "8de9a9d5-da2d-4758-ab5e-b9c49a3abfda"
          }
        ],
        "partitions": [
          {
            "name": "_Farhana",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_IfatFeroji",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "42f08227-1d5a-4773-b33c-06205c741f04",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3ff08181-0c54-4f92-b16a-4c302bfda575",
        "partitions": [
          {
            "name": "_IfatFeroji",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Diponkor",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8456ada5-6107-4989-8fca-c9e4e0f99288",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "de155ae1-cd2a-41fa-9703-8795de7e3c09",
        "partitions": [
          {
            "name": "_Diponkor",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Yousuf",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d409d392-d728-480e-92d2-3f64bb2ba8ad",
            "sourceColumn": "Column1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d852dfd9-3474-446e-94b5-7053e9637de4",
        "partitions": [
          {
            "name": "_Yousuf",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}